version: '2'
services:
  master:
    image: ros:kinetic
    container_name: master
    ports:
      - "11311:11311"
    command:
      - roscore

  talker:
    image: ros:kinetic
    container_name: talker
    depends_on:
      - master
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311"
    command: rostopic pub helloTopic std_msgs/String "hello world" --rate=0.5

  listener:
    image: ros:kinetic
    container_name: listener
    depends_on:
      - master
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: rostopic echo helloTopic