version: '2'
services:
  master:
    image: ros:melodic
    container_name: master
    ports:
      - "11311:11311"
    command:
      - roscore

  talker:
    build: ./talker
    container_name: talker
    depends_on:
      - master
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311"
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && rosrun talker talker.py"

  listener:
    build: ./listener
    container_name: listener
    depends_on:
      - master
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: /bin/bash -c "source /ros_ws/devel/setup.bash && rosrun listener listener.py"